"""create audit_log table

Revision ID: 54f28174be18
Revises: 
Create Date: 2026-08-20 03:27:21.191491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f28174be18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('CREATE_USER', 'RESET_PASSWORD', 'CHANGE_TIER', 'DISABLE_USER', 'ENABLE_USER', name='auditaction'), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
