"""add target_name column to audit_log

Revision ID: 63fb53e2db4d
Revises: 54f28174be18
Create Date: 2026-08-20 04:05:35.621986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fb53e2db4d'
down_revision = '54f28174be18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default='' 是必须的——如果这个表已经有历史行（比如线上已经跑了一
    # 阵子），直接加一个 NOT NULL 且无默认值的列会失败。给个空字符串默认值，
    # 新代码写入时始终会显式传 target_name（见 audit_service.record），这个
    # server_default 只是为了让 ALTER TABLE 本身能跑通。
    op.add_column('audit_log', sa.Column('target_name', sa.String(length=255), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'target_name')
    # ### end Alembic commands ###
